const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: '120',
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: '10',
            description: 'High quality Sports product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: '150',
            countInStock: 0,
            brand: 'Adidas',
            rating: '3',
            numReviews: '12',
            description: 'Cotton Cycling product',
        },
        {
            _id: '3',
            name: 'Lacosta Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: '230',
            countInStock: 20,
            brand: 'Lacosta',
            rating: '4.5',
            numReviews: '17',
            description: 'Silk Relaxing product',
        },
        {
            _id: '4',
            name: 'Versace Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: '170',
            countInStock: 8,
            brand: 'Nike',
            rating: '2.0',
            numReviews: '10',
            description: 'Rugged product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: '110',
            countInStock: 2,
            brand: 'Puma',
            rating: '3.5',
            numReviews: '28',
            description: 'Crisp daily wear product',
        },
        {
            _id: '6',
            name: 'Locosta Slim Shirt',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: '190',
            countInStock: 3,
            brand: 'Nike',
            rating: '4.5',
            numReviews: '10',
            description: 'Satin  product',
        },
        {
            _id: '7',
            name: 'MNM Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: '120',
            countInStock: 5,
            brand: 'Nike',
            rating: '4.5',
            numReviews: '10',
            description: 'Flexibleproduct',
        },
        {
            _id: '8',
            name: 'V Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: '120',
            countInStock: 4,
            brand: 'Nike',
            rating: '3',
            numReviews: '10',
            description: 'Stretchable product',
        }
    ]
};

 export default data;